name: DSDrender
channels:
  - anaconda
  - alubbock
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bidict
  - pysb
  - networkx
  - matplotlib
  - pyqt
  - graphviz
  - pygraphviz
  - cppyy
  - pip
  - pip:
      - ogdf-python
      - pydot
