name: DSDrender
channels:
  - anaconda
  - alubbock
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - bidict
  - pysb
  - networkx
  - matplotlib
  - pyqt
  - graphviz
  - pygraphviz
  - pip
  - pip:
    - ogdf-python
    - pydot
